package BitManipulationPrep;

import java.util.Arrays;

public class BitManipulationPrep {

    /*
    * Power of Two
    *
    Given an integer n, return true if it is a power of two. Otherwise, return false.

    An integer n is a power of two, if there exists an integer x such that n == 2x.
    * */
    public static boolean isPowerOfTwo(int n) {
        if (n > 0) {
            return (n & (n - 1)) == 0;
        }
        return false;
    }

    /*
    * Power of Four
    Given an integer n, return true if it is a power of four. Otherwise, return false.

    An integer n is a power of four, if there exists an integer x such that n == 4x.
    * */
    public static boolean isPowerOfFour(int n) {
        // Step 1: must be positive
        if (n <= 0) {
            return false;
        }

        // Step 2: must be power of 2 (only one set bit)
        if ((n & (n - 1)) != 0) {
            return false;
        }

        // Step 3: that set bit must be in even position
        return (n & 0x55555555) != 0;
    }

    /*
    * Single Number
    Given a non-empty array of integers nums, every element appears twice except for one. Find that single one.

    You must implement a solution with a linear runtime complexity and use only constant extra space.
    * */
    public static int singleNumber(int[] nums) {
        int result = 0;

        for (int num : nums) {
            result ^= num;
        }

        return result;
    }

    /*
    * Number of 1 Bits
    Given a positive integer n, write a function that returns the number of set bits in its binary representation
    * (also known as the Hamming weight).
    * */

    public static int hammingWeight(int n) {
        StringBuilder sb = new StringBuilder();
        while (n != 0) {
            int remainder = n % 2;
            n /= 2;
            sb.append(remainder);
        }

        int count = 0;
        for (int i = 0; i < sb.length(); i++) {
            if (sb.charAt(i) == '1') {
                count++;
            }
        }
        return count;
    }


    /*
    * Find the Difference
    You are given two strings s and t.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Return the letter that was added to t.



    Example 1:

    Input: s = "abcd", t = "abcde"
    Output: "e"
    Explanation: 'e' is the letter that was added.
    Example 2:

    Input: s = "", t = "y"
    Output: "y"
    * */

    public static char findTheDifference(String s, String t) {
        char[] s1 = s.toCharArray();
        char[] t1 = t.toCharArray();

        Arrays.sort(s1);
        Arrays.sort(t1);

        for (int i = 0; i < s1.length; i++) {
            if (s1[i] != t1[i]) {
                return t1[i];
            }
        }

        return t1[t1.length - 1];
    }



    public static void main(String[] args) {
        int[] nums = {2,2,1};
        int n = 8;
        System.out.println(hammingWeight(n));
    }
}
